# Generated by Django 5.2 on 2025-05-04 12:39

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/default_avatar.jpg', upload_to=user.models.user_directory_path),
        ),
    ]
